---
- name: Install helm
  hosts: with_login_tools
  gather_facts: true

  tasks:
    - name: Install helm via Homebrew (macOS)
      shell: /opt/homebrew/bin/brew install helm
      args:
        creates: /opt/homebrew/bin/helm
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install helm via apt (Debian)
      apt:
        name: helm
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install helm via pacman (Arch)
      pacman:
        name: helm
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Archlinux"
