---
- name: Install core CLI tools via Homebrew
  shell: /opt/homebrew/bin/brew install {{ item }}
  args:
    creates: /opt/homebrew/bin/{{ item }}
  loop:
    - sd
    - fd
    - ripgrep
    - fzf
    - jq
    - bat
    - eza
    - tree
    - wget
    - yt-dlp
    - ffmpeg
    - pandoc

- name: Install imagemagick
  shell: /opt/homebrew/bin/brew install imagemagick
  args:
    creates: /opt/homebrew/bin/magick
